### ISSUE TITLE
build YaSlicer through vs2015

### ISSUE THREAD

**Issue by Eric-Hsia** [mr-MOD/YaSlicer#1]
Hi, when I build the YaSlicer through vs2015, it has below errors, do you have any suggestions, and I have installed dependencies, thanks.
![build error](https://user-images.githubusercontent.com/20067709/38485527-a60b626e-3c0c-11e8-967d-a1c9e7eaa961.jpg)

**Comment by mr-MOD** [comment]
@Eric-Hsia, do you have VS2017 also installed? If you have, this is the most probable reason why dependencies are not visible in VS2015, they are just probably built for VS2017. Need vcpkg verbose logs to confirm this.

**Comment by Eric-Hsia** [comment]
Hi, thanks very much in advance, and which stl type it can slice, binary or ASCII. By the way, I have manually set the dependecies on vs2015, then compiled below errors, common module seems compile fine, 
![lnk2019](https://user-images.githubusercontent.com/20067709/38546636-b74c5064-3cdf-11e8-889b-6c0430a252e8.jpg)

**Comment by mr-MOD** [comment]
@Eric-Hsia it seems like Renderer.cpp is not added to Slicer project.

And currently YaSlicer can handle only binary STL models.

**Comment by Eric-Hsia** [comment]
@mr-MOD it's strange, I added all source file and .h, just few functions have this issue.

**Comment by Eric-Hsia** [comment]
@mr-MOD Hi, another quetion, the software need bcm_host.h and X11/X.h, what dependecies need?

**Comment by mr-MOD** [comment]
Hi, bcm_host.h and X11/X.h are for Raspberry/Linux, you don't need them on Windows. So exclude GlContextRPi.cpp/GlContextRPi.h and GlContextX.cpp/GlContextX.h from project.

**Comment by mr-MOD** [comment]
Regarding the problem with functions from Renderer.cpp, could you please share complete Build log from Visual Studio Output window ?

**Comment by Eric-Hsia** [comment]
Hi, I found few files were exclude from the project, then I include them and exclude GlContextRPi.cpp/GlContextRPi.h, it compiled fine. but I have no idea how to use it, can you help? shall I edit the config.cfg by myself? Thanks.

**Comment by mr-MOD** [comment]
@Eric-Hsia I have fixed couple issues for config file being non-optional, please pull updates.
Also updated readme, you may use command line shown there for quick start.

**Comment by Eric-Hsia** [comment]
I see, thanks very much:d
